name: Issue Notifier

on:
  workflow_call:
    inputs:
      zapier_webhook_url:
        required: true
        type: string

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Zapier Webhook
        run: |
          curl -X POST ${{ inputs.zapier_webhook_url }} \
          -H "Content-Type: application/json" \
          -d '{
            "repo": "${{ github.repository }}",
            "action": "${{ github.event.action }}",
            "issue_number": "${{ github.event.issue.number }}",
            "title": "${{ github.event.issue.title }}",
            assignee: ${{ github.event.issue.assignee && github.event.issue.assignee.login || 'Unassigned' }},
            "url": "${{ github.event.issue.html_url }}"
          }'

