name: Trigger Issue Notifier

on:
  issues:
    types: [opened, closed, assigned]

jobs:
  call-notifier:
    uses: Mitra-Dev/github-actions-workflows/.github/workflows/issue-notifier.yml@main
    secrets:
      OUTLOOK_EMAIL: ${{ secrets.OUTLOOK_EMAIL }}
      OUTLOOK_APP_PASSWORD: ${{ secrets.OUTLOOK_APP_PASSWORD }}
    with:
      helpdesk_email: apps@mitra.mw
