name: Issue Notifier

on:
  workflow_call:
    inputs:
      helpdesk_email:
        required: true
        type: string
    secrets:
      OUTLOOK_EMAIL:
        required: true
      OUTLOOK_APP_PASSWORD:
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        run: |
          echo "Sending email to ${{ inputs.helpdesk_email }}"
          # your email logic here using ${{ secrets.OUTLOOK_EMAIL }} and ${{ secrets.OUTLOOK_APP_PASSWORD }}
